options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: bash
    args:
      - -c
      - |
        gsutil -m rm -r gs://YOUR_BUCKET_NAME/** || true

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - gsutil
      - -m
      - cp
      - -r
      - .
      - gs://dual-axis-illusion
